services:
  web:
    build: .
    image: my-django-app
    container_name: photoapp-web
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env.dev
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "82:80"  # HOST:CONTAINER → maps localhost:82 to nginx container:80
      - "443:443"  # Allow HTTPS
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  redis:
    image: redis:7
    # ports:
    #   - "6379:6379"
    restart: always
    
  celery:
    image: ashwynrangani/my-django-app:latest
    command: celery -A mysite worker --loglevel=info
    env_file:
      - .env.dev
    depends_on:
      - redis
    restart: always
    volumes:
      - .:/app
  
  #celery_beat:
   #image: ashwynrangani/my-django-app:latest
    #command: celery -A mysite beat --loglevel=info
    #env_file:
     # - .env.dev
    #depends_on:
     # - redis
    #restart: always
    #volumes:
     # - .:/app
    
 

volumes:
  static_volume:
  
  
