# Generated by Django 5.1.4 on 2025-10-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_face_search_queries', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
