# Generated by Django 5.1.4 on 2025-03-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='/static/images/avatar_default.webp', upload_to='profile_pics/'),
        ),
    ]
