# Generated by Django 5.1.4 on 2025-12-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0004_alter_sitestats_photographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public_gallery_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='public_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
