# Generated by Django 5.1.4 on 2025-03-23 13:32

import photoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0005_remove_event_barcode_url_remove_event_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photoapp.models.event_photo_path),
        ),
    ]
