# Generated by Django 5.1.4 on 2025-12-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0005_event_is_public_gallery_enabled_event_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='public_token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
