# Generated by Django 5.1.4 on 2025-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='face_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
