# Generated by Django 5.1.4 on 2026-01-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0006_alter_event_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='studio_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
