# Generated by Django 5.1.4 on 2025-04-01 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0007_alter_photo_face_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='face_embedding',
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.JSONField(blank=True, null=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encodings', to='photoapp.photo')),
            ],
        ),
    ]
