# Generated by Django 5.1.4 on 2026-01-25 06:20

import photoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0007_event_studio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='large_image',
            field=models.ImageField(blank=True, null=True, upload_to=photoapp.models.large_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='medium_image',
            field=models.ImageField(blank=True, null=True, upload_to=photoapp.models.medium_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumb_image',
            field=models.ImageField(blank=True, null=True, upload_to=photoapp.models.thumb_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='branded_image',
            field=models.ImageField(blank=True, null=True, upload_to=photoapp.models.branded_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=photoapp.models.original_path),
        ),
    ]
