# Generated by Django 5.1.4 on 2026-01-26 18:55

import photoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0008_photo_large_image_photo_medium_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='branded_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=photoapp.models.branded_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(max_length=500, upload_to=photoapp.models.original_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='large_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=photoapp.models.large_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='medium_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=photoapp.models.medium_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumb_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=photoapp.models.thumb_path),
        ),
    ]
