# Generated by Django 5.1.4 on 2025-04-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0008_remove_photo_face_embedding_faceencoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceencoding',
            name='encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
