# Generated by Django 5.1.4 on 2026-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0009_alter_photo_branded_image_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public_gallery_downloadable',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
