# Generated by Django 5.1.4 on 2025-04-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0009_alter_faceencoding_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
