# Generated by Django 5.1.4 on 2025-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0010_photo_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='branding_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='event',
            name='branding_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_branding',
            field=models.BooleanField(default=False),
        ),
    ]
