# Generated by Django 5.1.4 on 2026-02-24 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0010_event_is_public_gallery_downloadable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_find_photos_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subevents', to='photoapp.event')),
            ],
            options={
                'ordering': ['order', 'date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='subevent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='photoapp.subevent'),
        ),
    ]
