# Generated by Django 5.1.4 on 2026-05-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0011_event_is_find_photos_enabled_subevent_photo_subevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='branding_font',
            field=models.CharField(choices=[('elegant', 'Elegant'), ('modern', 'Modern'), ('classic', 'Classic'), ('stylish', 'Stylish'), ('luxury', 'Luxury'), ('handwritten', 'Handwritten'), ('ultra_modern', 'Ultra Modern')], default='modern', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='branding_position',
            field=models.CharField(choices=[('bottom_right', 'Bottom Right'), ('bottom_left', 'Bottom Left'), ('bottom_center', 'Bottom Center'), ('top_right', 'Top Right')], default='bottom_right', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='branding_text_style',
            field=models.CharField(choices=[('box', 'Frosted Box'), ('plain', 'Plain Text')], default='box', max_length=10),
        ),
    ]
