# Generated by Django 5.1.4 on 2025-04-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0011_event_branding_image_event_branding_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_branding',
            new_name='branding_enabled',
        ),
    ]
