# Generated by Django 5.1.4 on 2026-05-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0012_event_branding_font_event_branding_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='branding_opacity',
            field=models.PositiveSmallIntegerField(default=78),
        ),
    ]
