# Generated by Django 5.1.4 on 2025-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0013_eventsubscription_payment_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('PER_EVENT', 'Per Event'), ('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('PER_EVENT', 'Per Event'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='FREE', max_length=20),
        ),
        migrations.DeleteModel(
            name='EventSubscription',
        ),
    ]
