# Generated by Django 5.1.4 on 2025-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0014_alter_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
