# Generated by Django 5.1.4 on 2025-05-05 18:59

import photoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0015_subscription_last_notified_subscription_unsubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='branded_image',
            field=models.ImageField(blank=True, null=True, upload_to=photoapp.models.event_photo_branded_path),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_branded',
            field=models.BooleanField(default=False),
        ),
    ]
