# Generated by Django 5.1.4 on 2025-05-19 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0016_photo_branded_image_photo_is_branded'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='customer_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='display_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='photoapp.event')),
            ],
        ),
    ]
