# Generated by Django 5.1.4 on 2025-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0017_photo_customer_selected_photo_display_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_downloadable',
            field=models.BooleanField(default=False),
        ),
    ]
