# Generated by Django 5.1.4 on 2025-05-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0018_event_is_downloadable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_downloadable',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
